/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.employees.Employee.kafka.avro.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class PersonalDetails extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2346008268929607202L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PersonalDetails\",\"namespace\":\"com.employees.Employee.kafka.avro.model\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"Name\",\"type\":\"string\"},{\"name\":\"LastName\",\"type\":\"string\"},{\"name\":\"Age\",\"type\":\"int\"},{\"name\":\"Sex\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PersonalDetails> ENCODER =
      new BinaryMessageEncoder<PersonalDetails>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PersonalDetails> DECODER =
      new BinaryMessageDecoder<PersonalDetails>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<PersonalDetails> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<PersonalDetails> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PersonalDetails>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this PersonalDetails to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a PersonalDetails from a ByteBuffer. */
  public static PersonalDetails fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int id;
  @Deprecated public java.lang.CharSequence Name;
  @Deprecated public java.lang.CharSequence LastName;
  @Deprecated public int Age;
  @Deprecated public java.lang.CharSequence Sex;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PersonalDetails() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param Name The new value for Name
   * @param LastName The new value for LastName
   * @param Age The new value for Age
   * @param Sex The new value for Sex
   */
  public PersonalDetails(java.lang.Integer id, java.lang.CharSequence Name, java.lang.CharSequence LastName, java.lang.Integer Age, java.lang.CharSequence Sex) {
    this.id = id;
    this.Name = Name;
    this.LastName = LastName;
    this.Age = Age;
    this.Sex = Sex;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return Name;
    case 2: return LastName;
    case 3: return Age;
    case 4: return Sex;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: Name = (java.lang.CharSequence)value$; break;
    case 2: LastName = (java.lang.CharSequence)value$; break;
    case 3: Age = (java.lang.Integer)value$; break;
    case 4: Sex = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'Name' field.
   * @return The value of the 'Name' field.
   */
  public java.lang.CharSequence getName() {
    return Name;
  }

  /**
   * Sets the value of the 'Name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.Name = value;
  }

  /**
   * Gets the value of the 'LastName' field.
   * @return The value of the 'LastName' field.
   */
  public java.lang.CharSequence getLastName() {
    return LastName;
  }

  /**
   * Sets the value of the 'LastName' field.
   * @param value the value to set.
   */
  public void setLastName(java.lang.CharSequence value) {
    this.LastName = value;
  }

  /**
   * Gets the value of the 'Age' field.
   * @return The value of the 'Age' field.
   */
  public java.lang.Integer getAge() {
    return Age;
  }

  /**
   * Sets the value of the 'Age' field.
   * @param value the value to set.
   */
  public void setAge(java.lang.Integer value) {
    this.Age = value;
  }

  /**
   * Gets the value of the 'Sex' field.
   * @return The value of the 'Sex' field.
   */
  public java.lang.CharSequence getSex() {
    return Sex;
  }

  /**
   * Sets the value of the 'Sex' field.
   * @param value the value to set.
   */
  public void setSex(java.lang.CharSequence value) {
    this.Sex = value;
  }

  /**
   * Creates a new PersonalDetails RecordBuilder.
   * @return A new PersonalDetails RecordBuilder
   */
  public static com.employees.Employee.kafka.avro.model.PersonalDetails.Builder newBuilder() {
    return new com.employees.Employee.kafka.avro.model.PersonalDetails.Builder();
  }

  /**
   * Creates a new PersonalDetails RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PersonalDetails RecordBuilder
   */
  public static com.employees.Employee.kafka.avro.model.PersonalDetails.Builder newBuilder(com.employees.Employee.kafka.avro.model.PersonalDetails.Builder other) {
    return new com.employees.Employee.kafka.avro.model.PersonalDetails.Builder(other);
  }

  /**
   * Creates a new PersonalDetails RecordBuilder by copying an existing PersonalDetails instance.
   * @param other The existing instance to copy.
   * @return A new PersonalDetails RecordBuilder
   */
  public static com.employees.Employee.kafka.avro.model.PersonalDetails.Builder newBuilder(com.employees.Employee.kafka.avro.model.PersonalDetails other) {
    return new com.employees.Employee.kafka.avro.model.PersonalDetails.Builder(other);
  }

  /**
   * RecordBuilder for PersonalDetails instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PersonalDetails>
    implements org.apache.avro.data.RecordBuilder<PersonalDetails> {

    private int id;
    private java.lang.CharSequence Name;
    private java.lang.CharSequence LastName;
    private int Age;
    private java.lang.CharSequence Sex;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.employees.Employee.kafka.avro.model.PersonalDetails.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Name)) {
        this.Name = data().deepCopy(fields()[1].schema(), other.Name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.LastName)) {
        this.LastName = data().deepCopy(fields()[2].schema(), other.LastName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.Age)) {
        this.Age = data().deepCopy(fields()[3].schema(), other.Age);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.Sex)) {
        this.Sex = data().deepCopy(fields()[4].schema(), other.Sex);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing PersonalDetails instance
     * @param other The existing instance to copy.
     */
    private Builder(com.employees.Employee.kafka.avro.model.PersonalDetails other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Name)) {
        this.Name = data().deepCopy(fields()[1].schema(), other.Name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.LastName)) {
        this.LastName = data().deepCopy(fields()[2].schema(), other.LastName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.Age)) {
        this.Age = data().deepCopy(fields()[3].schema(), other.Age);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.Sex)) {
        this.Sex = data().deepCopy(fields()[4].schema(), other.Sex);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Integer getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.employees.Employee.kafka.avro.model.PersonalDetails.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.employees.Employee.kafka.avro.model.PersonalDetails.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return Name;
    }

    /**
      * Sets the value of the 'Name' field.
      * @param value The value of 'Name'.
      * @return This builder.
      */
    public com.employees.Employee.kafka.avro.model.PersonalDetails.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.Name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Name' field has been set.
      * @return True if the 'Name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'Name' field.
      * @return This builder.
      */
    public com.employees.Employee.kafka.avro.model.PersonalDetails.Builder clearName() {
      Name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'LastName' field.
      * @return The value.
      */
    public java.lang.CharSequence getLastName() {
      return LastName;
    }

    /**
      * Sets the value of the 'LastName' field.
      * @param value The value of 'LastName'.
      * @return This builder.
      */
    public com.employees.Employee.kafka.avro.model.PersonalDetails.Builder setLastName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.LastName = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'LastName' field has been set.
      * @return True if the 'LastName' field has been set, false otherwise.
      */
    public boolean hasLastName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'LastName' field.
      * @return This builder.
      */
    public com.employees.Employee.kafka.avro.model.PersonalDetails.Builder clearLastName() {
      LastName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'Age' field.
      * @return The value.
      */
    public java.lang.Integer getAge() {
      return Age;
    }

    /**
      * Sets the value of the 'Age' field.
      * @param value The value of 'Age'.
      * @return This builder.
      */
    public com.employees.Employee.kafka.avro.model.PersonalDetails.Builder setAge(int value) {
      validate(fields()[3], value);
      this.Age = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'Age' field has been set.
      * @return True if the 'Age' field has been set, false otherwise.
      */
    public boolean hasAge() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'Age' field.
      * @return This builder.
      */
    public com.employees.Employee.kafka.avro.model.PersonalDetails.Builder clearAge() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'Sex' field.
      * @return The value.
      */
    public java.lang.CharSequence getSex() {
      return Sex;
    }

    /**
      * Sets the value of the 'Sex' field.
      * @param value The value of 'Sex'.
      * @return This builder.
      */
    public com.employees.Employee.kafka.avro.model.PersonalDetails.Builder setSex(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.Sex = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'Sex' field has been set.
      * @return True if the 'Sex' field has been set, false otherwise.
      */
    public boolean hasSex() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'Sex' field.
      * @return This builder.
      */
    public com.employees.Employee.kafka.avro.model.PersonalDetails.Builder clearSex() {
      Sex = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PersonalDetails build() {
      try {
        PersonalDetails record = new PersonalDetails();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.Name = fieldSetFlags()[1] ? this.Name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.LastName = fieldSetFlags()[2] ? this.LastName : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.Age = fieldSetFlags()[3] ? this.Age : (java.lang.Integer) defaultValue(fields()[3]);
        record.Sex = fieldSetFlags()[4] ? this.Sex : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PersonalDetails>
    WRITER$ = (org.apache.avro.io.DatumWriter<PersonalDetails>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PersonalDetails>
    READER$ = (org.apache.avro.io.DatumReader<PersonalDetails>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
